public class Main {
    public static void main(String[] args) {
        //1
        Person p1 = new Person();
        Person p2 = new Person("Anand");
        Person p3 = new Person(22);
        Person p4 = new Person("Anand",22);
        // Person p5 = new Person(22,"Anand");


    }
}


// 1.  Define a Java class Person with private instance variables name and age.
//     Provide four constructors in the class,
//         one with no argument,
//         second with name only,
//         third with age only
//         fourth with name and age.
class Person{
    private String name;
    private int age;
    public Person(){}
    public Person(String n){name=n;}
    public Person(int a){age=a;}
    public Person(String n,int a){name=n;age=a;}

    //2
    Employee e1 = new Employee();
    Employee e2 = new Employee("Anand",1000000);
    // e2.getempid();


}

// 2.  Define a class Employee with private instance variables empid, name and salary.
//     Create a static variable to store an integer value(initially 0), which gets incremented
//     on instantiation, this value can be use to generate emptied so that every employee
//     has autogenerated unique empid. Define a private method to generate empid.
//     Provide two constructors in the class, one is taking two arguments (name and salary)
//     and the other one is non parameterised.
//     Non parameterised constructor ask anme and salary from the user.
class Employee{
    private int empid;
    private String name;
    private double salary;
    public static int count=0;
    {empid=++count;}
    private int getempid(){return empid;}
    public Employee(){}
    public Employee(String n,double s){name=n;salary=s;}
}

// 3.  Define a class Box with private instance variables length, breadth, and height.
//     Provide three constructors in the class,
//         first with no arguments,
//         second with one arguments,
//         third with three arguments.

// 4.  Define a class Time with private instance variables hr, min and sec.
//     Provide three constructors in the class,
//         first one takes no arguments,
//         second takes one argument as seconds,
//         and third takes three arguments for hour, min and seconds.
